# --- !Ups

ALTER TABLE activity ALTER COLUMN cost SET DATA  TYPE NUMERIC;

ALTER TABLE formula ALTER COLUMN cost SET DATA  TYPE NUMERIC;

ALTER TABLE session_card ALTER COLUMN cost SET DATA  TYPE NUMERIC;

ALTER TABLE child_day ALTER COLUMN amount_payed SET DATA  TYPE NUMERIC;

ALTER TABLE playground_day ALTER COLUMN money_income SET DATA  TYPE NUMERIC;

ALTER TABLE basic_user ALTER COLUMN not_payed SET DATA  TYPE NUMERIC;




# --- !Downs

ALTER TABLE activity ALTER COLUMN cost Set DATA TYPE FLOAT ;

ALTER TABLE formula ALTER COLUMN cost Set DATA TYPE FLOAT ;

ALTER TABLE session_card ALTER COLUMN cost Set DATA TYPE FLOAT ;

ALTER TABLE child_day ALTER COLUMN amount_payed Set DATA TYPE FLOAT ;

ALTER TABLE playground_day ALTER COLUMN money_income Set DATA TYPE FLOAT ;

ALTER TABLE basic_user ALTER COLUMN not_payed Set DATA TYPE FLOAT ;